spring:
  datasource:
    url: jdbc:mariadb://15.164.85.227:3306/member-service
    username: test
    password: test
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: member-service
  profiles:
    include: credentials

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

token:
  secret: sample
