spring:
  datasource:
    url: jdbc:mariadb://15.164.85.227:3306/member-service
    username: test
    password: test
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: member-service
  profiles:
    include: credentials

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.164.85.227:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,info,metrics,prometheus

token:
  access-secret: sample
  refresh-secret: sample

42meet:
  server:
    host: http://42meet.kro.kr
    login: http://42meet.kro.kr/login
    redirect: http://42meet.kro.kr
    test: http://localhost:3000